Userfriendly\Bundle\SocialUserBundle\Model\UserEmailChangeRequest:
    type: entity
    table: user__emailchangerequest
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        email:
            type: string
            length: 255
        confirmationToken:
            column: confirmation_token
            type: string
            length: 255
            unique: true
            nullable: true
        confirmed:
            type: boolean
        updatedAt:
            column: updated_at
            type: datetime
            gedmo:
                timestampable:
                    on: update
        createdAt:
            column: created_at
            type: datetime
            gedmo:
                timestampable:
                    on: create
    manyToOne:
        user:
            targetEntity: Userfriendly\Bundle\SocialUserBundle\Model\UserInterface
            joinColumn:
                name: user_id
                referencedColumnName: id
            cascade: ["persist"]